### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [JakeCrandell/proj9-railsapp#1]
This is looking good apart from the indentation. The standard indentation for Ruby (`.rb`) files, such as [`static_helper.rb`](https://github.com/JakeCrandell/proj9-railsapp/blob/master/app/helpers/static_helper.rb) is two-space soft-tabs instead of hard-tabs. And in Rails projects, it's actually best practice to have _every_ file use two-space soft-tabs.

Can you [reconfigure your text editor](https://github.com/chrisvfritz/tc359_cheatsheets/blob/master/ruby/indentation.md) to use two-space soft-tabs instead? And then afterwards, update all your files to use with that indentation. You may also find [this video](https://www.youtube.com/watch?v=_JFIeY46sIU) and [this video](https://www.youtube.com/watch?v=GMf8dlrEbB4) helpful for Sublime Text.

Let me know when you've updated these and I'll take another look. If you get stuck, also please don't hesitate and I'll be happy to point you in the right direction.

**Comment by JakeCrandell** [comment]
Ok, I've reconfigured my text editor and I think I changed all the files I needed to. The new files have been pushed to Git and Heroku.

**Comment by chrisvfritz** [comment]
:+1: Looks really good!
